<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DOC [

	<!ELEMENT DOC (DATATYPES,TSREF)>
	<!ELEMENT DATATYPES (ENTRY*)>
	<!ELEMENT TSREF (ENTRY)+>
	<!ELEMENT ENTRY (DESCRIPTION, DATATYPE*, POSIBLEVALUES*, DEFAULT*, COBJ*, PROTOTYPE*, EXAMPLE*, CHILDREN*, VARIANT* )>
	<!ELEMENT DESCRIPTION  (#PCDATA)>
	<!ELEMENT DATATYPE (#PCDATA)>
	<!ELEMENT PROTOTYPE (#PCDATA)>
	<!ELEMENT COBJ (#PCDATA)>
	<!ELEMENT EXAMPLE (#PCDATA)>
	<!ELEMENT DEFAULT (#PCDATA)>
	<!ELEMENT POSIBLEVALUES (#PCDATA)>
	<!ELEMENT CHILDREN (ENTRY*,TYPEREF*)>
	<!ELEMENT TYPEREF (#PCDATA)>
	<!ELEMENT VARIANT (ENTRY*)>

	<!ATTLIST ENTRY KEY CDATA #REQUIRED>
	<!ATTLIST ENTRY REF CDATA #IMPLIED>
	<!ATTLIST TYPEREF KEY CDATA #REQUIRED>
	<!ATTLIST TYPEREF REF CDATA #REQUIRED>

]>

<DOC>

	<DATATYPES>

		<ENTRY REF="pager.pagerClassName" KEY="pagerClassName">
			<DESCRIPTION>Name of the PHP Class of this pager.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE>pagerClassName = DefaultPager</EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="pager.templatePath" KEY="templatePath">
			<DESCRIPTION>Name of the template class for this pager.</DESCRIPTION>
			<DATATYPE>String Path</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE>templatePath = EXT:pt_extlist/Resources/Private/Templates/Pager/Default.html</EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="pager.enabled" KEY="enabled">
			<DESCRIPTION>Indicates if this pager is enabled.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="pager.showFirstLink" KEY="showFirstLink">
			<DESCRIPTION>Indicates if the firstLink is shown.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="pager.showPreviousFilter" KEY="showPreviousFilter">
			<DESCRIPTION>Indicates if the previousLink is shown.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="pager.showLastLink" KEY="showLastLink">
			<DESCRIPTION>Indicates if the firstLink is shown.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="pager.showNextLink" KEY="showNextLink">
			<DESCRIPTION>Indicates if the nextLink is shown.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>

		<ENTRY REF="filter.filterIdentifier" KEY="filterIdentifier">
			<DESCRIPTION>The unique identifier of this filter.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.label" KEY="label">
			<DESCRIPTION>The label which is displayed beside the filter.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.description" KEY="description">
			<DESCRIPTION>An optional description string, that describes the filters functions.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.defaultValue" KEY="defaultValue">
			<DESCRIPTION>The default value which is shown or selected by default.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE><![CDATA[
// Selects key 3 as default Value
defaultValue = 3

// Selects multiple values in a multi value	filter (3 and 18)
defaultValue {
	10 = 3
	20 = 18
}

// Selects current user as default in an user select list
defaultValue.cObject = TEXT
defaultValue.cObject.data = TSFE:fe_user|user|username
			]]></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.accessGroups" KEY="accessGroups">
			<DESCRIPTION>Comma separated list of user groups wich have access to this filter.</DESCRIPTION>
			<DATATYPE>Comma eparated list.</DATATYPE>
			<POSIBLEVALUES>TYPO3 Group Ids</POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.fieldIdentifier" KEY="fieldIdentifier">
			<DESCRIPTION>WARNING: Which one to choose??? Identifier of a defined data field. The filter affects on this data field. If more than on fieldIdentifier is given, the resulting query is linked with or. Either a single identifier of a defined field, a comma separated list of identifiers or '*' to use all defined fields.</DESCRIPTION>
			<DATATYPE>fieldIdentifier or *</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE><![CDATA[
// use a single field
fieldIdentifier = cn_short_local

// use a list of fields
fieldIdentifier = cn_short_local, name_local

// use every defined field
fieldIdentifier = *
			]]></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.filterClassName" KEY="filterClassName">
			<DESCRIPTION>Name of the PHP Class of this filter.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE>Tx_PtExtlist_Domain_Model_Filter_StringFilter</EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.partialPath" KEY="partialPath">
			<DESCRIPTION></DESCRIPTION>
			<DATATYPE></DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.invert" KEY="invert">
			<DESCRIPTION>Invert the constraint of this filter.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>0</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.invertable" KEY="invertable">
			<DESCRIPTION>Show a controle to invert this filter.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>0</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.renderObj" KEY="renderObj">
			<DESCRIPTION>A cObject definition to render every selct option. With {field:FIELDNAME} you can accedd all display Fields. Additional the implicit defined fields [allDisplayFields] for all defined displayFields and [rowCount] for the count of the entrys with this option  are possible.</DESCRIPTION>
			<DATATYPE>String (cObject)</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT><![CDATA[
renderObj {
	dataWrap = {field:allDisplayFields} ({field:rowCount})
}
			]]></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.displayFields" KEY="displayFields">
			<DESCRIPTION>One or multiple identifiers of previously defined data fields.</DESCRIPTION>
			<DATATYPE>String / Comma separated list</DATATYPE>
			<POSIBLEVALUES>Previously defined field indentifier.</POSIBLEVALUES>
			<DEFAULT>If not set, the field defined in fieldIdentifier is used.</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.multiple" KEY="multiple">
			<DESCRIPTION></DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>0</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.excludeFilters" KEY="excludeFilters">
			<DESCRIPTION>List of filters that are not considered for the group query of this filter.</DESCRIPTION>
			<DATATYPE>String / Comma separated list of filterIdentifiers.</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.showRowCount" KEY="showRowCount">
			<DESCRIPTION>Show the row count if the select filter is filled with grouped data.

Info for use with MySQL Backend
In case this list is grouped by any field, showRowCount also implies the following manipulation to the original list query:
1. ShowRowCount is activated, In this case we have to build the list first and then use this list as source to calculate the selectable rows and the count. This has the drawback, that options are not displayed, if grouped within the list.
2. ShowRowCount is not activated: In this case, we exchange the original grouping fields with the fields needed by the filter.

            </DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>1</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.submitOnChange" KEY="submitOnChange">
			<DESCRIPTION>Instant submit filter if a value is selected.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>0</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.resetToDefaultValue" KEY="resetToDefaultValue">
			<DESCRIPTION>If a default value for a filter is set in TypoScript, the filter will be set to this value if it is resetted. If this is set to 0, the filter will be resetted to an empty value.</DESCRIPTION>
			<DATATYPE>Boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>0</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.inactiveOption" KEY="inactiveOption">
			<DESCRIPTION>Label of an option that is added to the select list. If this option is selected, the filter is inactive.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.inactiveValue" KEY="inactiveValue">
			<DESCRIPTION>The submitted value for the inactiveOption described above.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.breadCrumbString" KEY="breadCrumbString">
			<DESCRIPTION>Defines the string that is shown as breadcrumb for the filter. You can use '%v' for the filter's value and '%l' for the filter's label.</DESCRIPTION>
			<DATATYPE>String</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE>breadCrumbString = %l equals '%v'</EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.hidden" KEY="hidden">
			<DESCRIPTION>Hide the filter completely from the filterBox (don't render any output). This can be used in filters like the proxy filter or any filter that is only set via the extlistContext PHP methods.</DESCRIPTION>
			<DATATYPE>boolean</DATATYPE>
			<POSIBLEVALUES>0,1</POSIBLEVALUES>
			<DEFAULT>0</DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE></EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
		<ENTRY REF="filter.options" KEY="options">
			<DESCRIPTION>Defines explicit options to display in a data filter. If options are set, no data is fetched from the database. There are to variants to define the data. See the example for details.</DESCRIPTION>
			<DATATYPE>array</DATATYPE>
			<POSIBLEVALUES></POSIBLEVALUES>
			<DEFAULT></DEFAULT>
			<COBJ></COBJ>
			<PROTOTYPE></PROTOTYPE>
			<EXAMPLE>
# There are two variants to define the data

# Variant 1: Simple key / value
options {
	checkedin = Someone Checked in
	noonecheckedin = LLL:EXT:pt_ext/Resources/Private/Language/locallang_db.xml:tx_ext_domain_model_downloads.facility
}

# Variant 2: Use integer keys to define option order and subKeys key / value to define the options
10 {
	key = 1
	value = LLL:EXT:my_ext/locallang.xml:theLabelOfTheOption
}
20 {
	...
}
			</EXAMPLE>
			<CHILDREN></CHILDREN>
			<VARIANT></VARIANT>
		</ENTRY>
</DATATYPES>



	<TSREF>
		<ENTRY KEY="plugin.tx_ptextlist.settings">
			<DESCRIPTION>Main TS-key for all pt_extlist settings.</DESCRIPTION>
			<CHILDREN>
				<ENTRY KEY="listConfig">
					<DESCRIPTION>Holds configuration for all list identifiers configured by array key.</DESCRIPTION>
					<DATATYPE>Associative Array (listIdentifier => listConfiguration)</DATATYPE>
					<EXAMPLE><![CDATA[
plugin.tx_ptextlist.settings {

	listConfig {
		listIdentifier1 {

			# Here goes the configuration for your first list
			...
		}

		listIdentifier2 {

			# Here goes the configuration for your second list
			...
		}

		# Feel free to add more lists...
		...
	}
}]]></EXAMPLE>
					<CHILDREN>
						<ENTRY KEY="base">
							<DESCRIPTION>Basic settings for pt_extlist</DESCRIPTION>
							<DATATYPE></DATATYPE>
							<POSIBLEVALUES></POSIBLEVALUES>
							<DEFAULT></DEFAULT>
							<COBJ></COBJ>
							<PROTOTYPE></PROTOTYPE>
							<EXAMPLE></EXAMPLE>
							<CHILDREN>
								<ENTRY KEY="uncachedSessionStorageAdapter">
									<DESCRIPTION>Define the session storage adapter that should be used in uncached mode. Posible values are the classes described below or any other class that implements the interface Tx_PtExtbase_State_Session_Storage_AdapterInterface.</DESCRIPTION>
									<DATATYPE>String</DATATYPE>
									<POSIBLEVALUES><![CDATA[
Tx_PtExtbase_State_Session_Storage_SessionAdapter: Default browser session storage adapter.
Tx_PtExtbase_State_Session_Storage_FeUserSessionAdapter: TYPO3 fe_user bases session storage.
]]></POSIBLEVALUES>
									<DEFAULT>Tx_PtExtbase_State_Session_Storage_SessionAdapter</DEFAULT>
									<COBJ></COBJ>
									<PROTOTYPE></PROTOTYPE>
									<EXAMPLE></EXAMPLE>
									<CHILDREN></CHILDREN>
									<VARIANT></VARIANT>
								</ENTRY>
								<ENTRY KEY="cachedSessionStorageAdapter">
									<DESCRIPTION>Define the session storage adapter that should be used in cached mode. Posible values are the classes described below or any other class that implements the interface Tx_PtExtbase_State_Session_Storage_AdapterInterface.</DESCRIPTION>
									<DATATYPE>String</DATATYPE>
									<POSIBLEVALUES><![CDATA[
Tx_PtExtlist_Domain_StateAdapter_Storage_NullStorageAdapter: Hold every session variable as GET parameters in the URL. Use this adapter if you want to use realURL.
Tx_PtExtlist_Domain_StateAdapter_Storage_DBStorageAdapter: Save the session variables into the database and add an identifier for this db-entry to the GET variables. Use this adapter if you want to handle many parameters and keep the URL length constant.
]]></POSIBLEVALUES>
									<DEFAULT>Tx_PtExtlist_Domain_StateAdapter_Storage_NullStorageAdapter</DEFAULT>
									<COBJ></COBJ>
									<PROTOTYPE></PROTOTYPE>
									<EXAMPLE></EXAMPLE>
									<CHILDREN></CHILDREN>
									<VARIANT></VARIANT>
								</ENTRY>
								<ENTRY KEY="resetOnEmptySubmit">
									<DESCRIPTION>By setting this to "1", a list will be reset if there is no GP-Vars-Data for current request. You can use this, if you want a list to be in its default state every time you open the page on which the list is inserted.</DESCRIPTION>
									<DATATYPE>Boolean</DATATYPE>
									<POSIBLEVALUES>1,0</POSIBLEVALUES>
									<DEFAULT>0</DEFAULT>
								</ENTRY>
							</CHILDREN>
							<VARIANT></VARIANT>
						</ENTRY>
						<ENTRY KEY="[yourListId]">
							<DESCRIPTION>Holds configuration for a single list identifier. This is where the main part of your list configuration has to be set up.</DESCRIPTION>
							<EXAMPLE><![CDATA[
plugin.tx_ptextlist.settings {

	listConfig {
		demolist_mysql_01 {

			backendConfig < plugin.tx_ptextlist.prototype.backend.mysql
			backendConfig {
				...
			}

			fields {
				...
			}

			columns {
				...
			}

			filters {
				...
			}

			pager {
				...
			}
		}
	}
}
							]]></EXAMPLE>
							<CHILDREN>
								<ENTRY KEY="default">
									<DESCRIPTION>List default values.</DESCRIPTION>
									<DATATYPE></DATATYPE>
									<POSIBLEVALUES></POSIBLEVALUES>
									<DEFAULT></DEFAULT>
									<COBJ></COBJ>
									<PROTOTYPE></PROTOTYPE>
									<EXAMPLE></EXAMPLE>
									<CHILDREN>
										<ENTRY KEY="sortingColumn">
											<DESCRIPTION>The default sorting column while no other sorting ist set. Direction can be set with DESC or ASC after the column identifier.</DESCRIPTION>
											<DATATYPE>String</DATATYPE>
											<POSIBLEVALUES>Any column identifier</POSIBLEVALUES>
											<DEFAULT></DEFAULT>
											<COBJ></COBJ>
											<PROTOTYPE></PROTOTYPE>
											<EXAMPLE><![CDATA[
// use capital as default sorting column in ascending order
sortingColumn = capital

// use capital as default sorting column in descending order
sortingColumn = capital	DESC

											]]></EXAMPLE>
											<CHILDREN></CHILDREN>
											<VARIANT></VARIANT>
										</ENTRY>
									</CHILDREN>
									<VARIANT></VARIANT>
								</ENTRY>
                                <ENTRY KEY="cacheRendering">
                                    <DESCRIPTION>Set to 1 if you want to cache rendering of cells. Can slow down list creation, if values are all different and caching makes no sense.</DESCRIPTION>
                                    <DATATYPE>Boolean</DATATYPE>
                                    <POSIBLEVALUES></POSIBLEVALUES>
                                    <DEFAULT></DEFAULT>
                                    <COBJ></COBJ>
                                    <PROTOTYPE></PROTOTYPE>
                                    <EXAMPLE></EXAMPLE>
                                    <CHILDREN></CHILDREN>
                                    <VARIANT></VARIANT>
                                </ENTRY>
                                <ENTRY KEY="useIterationListData">
                                    <DESCRIPTION>If set to 1 the iterationListData is used instead of the default listData. While the listData provides an array of all data fetched from the database, which is then mapped and rendered completely, the iterationListData fetches, maps and renders a single row at a time. This has the big advantage, that only the memory for a single row object is consumed and only a constant amount of memory is needed, independent from the amoutn of rows. The disadvantage is, that a renderer is only able to process one single row, which makes it impossible to compute an aggregate on the fetched data.</DESCRIPTION>
                                    <DATATYPE>Boolean</DATATYPE>
                                    <POSIBLEVALUES></POSIBLEVALUES>
                                    <DEFAULT>1</DEFAULT>
                                    <COBJ></COBJ>
                                    <PROTOTYPE></PROTOTYPE>
                                    <EXAMPLE></EXAMPLE>
                                    <CHILDREN></CHILDREN>
                                    <VARIANT></VARIANT>
                                </ENTRY>
								<ENTRY KEY="backendConfig">
									<DESCRIPTION>Holds the configuration for the data backend to be used with this configuration. Configurable values depend on
									individual backend, e.g. TYPO3-Backend, MySQL-Backen, ExtBase-Backend etc.</DESCRIPTION>

									<VARIANT>

										<ENTRY KEY="backendConfig.mysql">
											<DESCRIPTION>Backend configuration for connecting to native MySQL databases. DSN needs to be configured.</DESCRIPTION>
											<PROTOTYPE>plugin.tx_ptextlist.prototype.backend.mysql</PROTOTYPE>
											<EXAMPLE><![CDATA[
backendConfig {

	dataSource {
		username = t3ry21ptldev
		password = xxxxxx
		databaseName = t3ry21ptldev
	}

	tables (
		City,
		Country
	)

	baseFromClause (
		Country
		INNER JOIN City ON City.CountryCode = Country.Code
		INNER JOIN CountryLanguage ON CountryLanguage.CountryCode = Country.Code
	)

	baseWhereClause (
	)

	baseGroupByClause (
		Country.Code, City.ID
	)
}
]]></EXAMPLE>
											<CHILDREN>
												<ENTRY KEY="datasource">
													<DESCRIPTION>Defines datasource for (MySQL) data backend.</DESCRIPTION>
													<DATATYPE></DATATYPE>
													<POSIBLEVALUES></POSIBLEVALUES>
													<DEFAULT></DEFAULT>
													<COBJ>0</COBJ>
													<PROTOTYPE></PROTOTYPE>
													<EXAMPLE><![CDATA[
dataSource {
	host = mysql.db.hoster.tld
	username = funnyrabbit
	password = xxxxxxx
	databaseName = rabbitsdatabase
}
]]></EXAMPLE>
													<CHILDREN>
														<ENTRY KEY="host">
															<DESCRIPTION>Defines hostname of mysql database server.</DESCRIPTION>
															<DATATYPE>String</DATATYPE>
															<POSIBLEVALUES>All valid addresses for servers (IP-Addresses and URLs)</POSIBLEVALUES>
															<DEFAULT>localhost</DEFAULT>
															<COBJ></COBJ>
															<PROTOTYPE></PROTOTYPE>
															<EXAMPLE></EXAMPLE>
															<CHILDREN></CHILDREN>
															<VARIANT></VARIANT>
														</ENTRY>
														<ENTRY KEY="port">
															<DESCRIPTION>Port number on which MySQL database server is listening.</DESCRIPTION>
															<DATATYPE>Int</DATATYPE>
															<POSIBLEVALUES>Any valid port number</POSIBLEVALUES>
															<DEFAULT>3306</DEFAULT>
															<COBJ></COBJ>
															<PROTOTYPE></PROTOTYPE>
															<EXAMPLE></EXAMPLE>
															<CHILDREN></CHILDREN>
															<VARIANT></VARIANT>
														</ENTRY>
														<ENTRY KEY="databaseName">
															<DESCRIPTION>Name of database to be used for connection.</DESCRIPTION>
															<DATATYPE>String</DATATYPE>
															<POSIBLEVALUES>Any valid database name</POSIBLEVALUES>
															<DEFAULT></DEFAULT>
															<COBJ></COBJ>
															<PROTOTYPE></PROTOTYPE>
															<EXAMPLE></EXAMPLE>
															<CHILDREN></CHILDREN>
															<VARIANT></VARIANT>
														</ENTRY>
														<ENTRY KEY="username">
															<DESCRIPTION>Username to be used for database connection.</DESCRIPTION>
															<DATATYPE>String</DATATYPE>
															<POSIBLEVALUES>Valid username for MySQL connection.</POSIBLEVALUES>
															<DEFAULT></DEFAULT>
															<COBJ></COBJ>
															<PROTOTYPE></PROTOTYPE>
															<EXAMPLE></EXAMPLE>
															<CHILDREN></CHILDREN>
															<VARIANT></VARIANT>
														</ENTRY>
														<ENTRY KEY="password">
															<DESCRIPTION>Password to be used for database connection.</DESCRIPTION>
															<DATATYPE>String</DATATYPE>
															<POSIBLEVALUES>Any valid password.</POSIBLEVALUES>
															<DEFAULT></DEFAULT>
															<COBJ></COBJ>
															<PROTOTYPE></PROTOTYPE>
															<EXAMPLE></EXAMPLE>
															<CHILDREN></CHILDREN>
															<VARIANT></VARIANT>
														</ENTRY>
													</CHILDREN>
													<VARIANT></VARIANT>
												</ENTRY>

												<ENTRY KEY="baseFromClause">
													<DESCRIPTION>Holds the FROM clause of a mysql query without the FROM keyword.</DESCRIPTION>
													<DATATYPE>String</DATATYPE>
													<POSIBLEVALUES></POSIBLEVALUES>
													<DEFAULT></DEFAULT>
													<COBJ>1</COBJ>
													<PROTOTYPE></PROTOTYPE>
													<EXAMPLE><![CDATA[
static_countries
LEFT JOIN static_territories AS	st_subcontinent	ON (static_countries.cn_parent_tr_iso_nr = st_subcontinent.tr_iso_nr)
													]]></EXAMPLE>
												</ENTRY>

												<ENTRY KEY="baseWhereClause">
													<DESCRIPTION>Holds the WHERE clause of a mysql query without the WHERE keyword.</DESCRIPTION>
													<DATATYPE></DATATYPE>
													<POSIBLEVALUES></POSIBLEVALUES>
													<DEFAULT></DEFAULT>
													<COBJ>1</COBJ>
													<PROTOTYPE></PROTOTYPE>
													<EXAMPLE><![CDATA[
# Example using cObject
baseWhereClause.cObject = COA
baseWhereClause.cObject {
	10 = TEXT
	10 {
		data = TSFE:fe_user|user|username
		noTrimWrap = | ticket.queue_id IN (SELECT queue_id FROM personal_queues WHERE user_id = (SELECT id FROM users WHERE login = "|")) |
	}
	20 = TEXT
	20 {
		data = TSFE:fe_user|user|username
		noTrimWrap = | AND ticket.user_id IN (1, (SELECT id FROM users WHERE login = "|")) |
	}
	30 = TEXT
	30 {
		data = TSFE:fe_user|user|username
		noTrimWrap = | OR ticket.user_id = (SELECT id FROM users WHERE login = "|") |
	}
}

# Example using  no cObject
baseWhereClause = fe_users.uid <> 0
													]]></EXAMPLE>

													<CHILDREN></CHILDREN>
													<VARIANT></VARIANT>
												</ENTRY>

												<ENTRY KEY="baseGroupByClause">
													<DESCRIPTION>Holds the GROUP BY clause of a mysql query without the GROUP BY keyword.</DESCRIPTION>
													<DATATYPE>String</DATATYPE>
													<COBJ>1</COBJ>
													<PROTOTYPE></PROTOTYPE>
													<EXAMPLE>st_continent</EXAMPLE>
												</ENTRY>
											</CHILDREN>
										</ENTRY>

										<ENTRY KEY="backendConfig.typo3">
											<DESCRIPTION>TYPO3 Backend. Inherits the Features from the MySql Backend but the datasource is already configured. The TYPO3 Backend handles enableFields automatically in where clauses.</DESCRIPTION>
											<DATATYPE></DATATYPE>
											<POSIBLEVALUES></POSIBLEVALUES>
											<DEFAULT></DEFAULT>
											<COBJ>0</COBJ>
											<PROTOTYPE></PROTOTYPE>
											<EXAMPLE><![CDATA[
backendConfig < plugin.tx_ptextlist.prototype.backend.typo3
backendConfig {
	tables (
		static_countries,
		static_territories st_continent,
		static_territories st_subcontinent
	)

	baseFromClause (
		static_countries
		LEFT JOIN static_territories AS st_subcontinent ON (static_countries.cn_parent_tr_iso_nr = st_subcontinent.tr_iso_nr)
		LEFT JOIN static_territories AS st_continent ON (st_subcontinent.tr_parent_iso_nr = st_continent.tr_iso_nr)
	)

	baseWhereClause (
		st_continent.tr_name_en <> ''
		AND st_subcontinent.tr_name_en <> ''
	)
}
											]]></EXAMPLE>
											<CHILDREN>
												<ENTRY KEY="tables">
													<DESCRIPTION>Define tables to be used with enable fields. TYPO3 special fields (deleted, hidden) are automatically applied to query.</DESCRIPTION>
													<DATATYPE>Comma seperated list of table names and aliases (optional).</DATATYPE>
													<POSIBLEVALUES></POSIBLEVALUES>
													<DEFAULT></DEFAULT>
													<COBJ>0</COBJ>
													<PROTOTYPE></PROTOTYPE>
													<EXAMPLE><![CDATA[
static_countries,
static_territories st_continent
													]]></EXAMPLE>
													<CHILDREN></CHILDREN>
													<VARIANT></VARIANT>
												</ENTRY>
												<ENTRY KEY="useEnableFields">
													<DESCRIPTION>Use enableFields for alle tables that are defined with key tables.</DESCRIPTION>
													<DATATYPE>Boolean</DATATYPE>
													<POSIBLEVALUES>0,1</POSIBLEVALUES>
													<DEFAULT>1</DEFAULT>
													<COBJ>0</COBJ>
													<PROTOTYPE></PROTOTYPE>
													<EXAMPLE>
													</EXAMPLE>
													<CHILDREN></CHILDREN>
													<VARIANT></VARIANT>
												</ENTRY>
											</CHILDREN>
											<VARIANT></VARIANT>
										</ENTRY>

										<ENTRY KEY="backendConfig.extbase">
											<DESCRIPTION>Extbase Repository Backend.</DESCRIPTION>
											<PROTOTYPE>plugin.tx_ptextlist.prototype.backend.extbase</PROTOTYPE>
										</ENTRY>
									</VARIANT>
								</ENTRY>
                                <ENTRY KEY="resetOnEmptySubmit">
                                    <DESCRIPTION>If this is set to 1, a list will be reset every time there is no
                                        GP-var data for current request. You can use this switch, if you want a list
                                        to be reset to its default settings every time you open up a page.</DESCRIPTION>
                                    <DATATYPE>Boolean</DATATYPE>
                                    <POSIBLEVALUES>0,1</POSIBLEVALUES>
                                    <DEFAULT>1</DEFAULT>
                                    <COBJ>0</COBJ>
                                    <PROTOTYPE></PROTOTYPE>
                                    <EXAMPLE>
                                    </EXAMPLE>